oasis-open/odata-rapid

- docs/rapid-pro-rsdl.md
Part of #43:
- no implicit top-level resources
- `type Query` defines the top-level readable resources
- `type Mutation` defines the top-level modifiable resources
> resources and navigation

- website/docusaurus.config.js
- website/src/components/rocket/animation.js
Building SSR was failing. Added some checks.
Website is available for preview on:
https://oasis-open.github.io/odata-rapid/
@sthagen We need to remove the domain from your private repo to enable it here
> Fix website SSR issues

- website/docusaurus.config.js
> chore: change website url to rapid.rocks

- website/docusaurus.config.js
- website/static/CNAME
Making very small fixes to enable website under: http://rapid.rocks
> Disable tutorial section and enable CNAME for website

- docs/rapid-pro-operations.md
- docs/rapid-pro-read.md
Fixes https://github.com/oasis-open/odata-rapid/issues/81
> Adapted example URLs

- reference/rapidpro-cli/tests/jetsons.graphql
> Jetsons example using GraphQL-inspired DSL

- tools/rsdl/dotnet/.vscode/launch.json
- tools/rsdl/dotnet/.vscode/tasks.json
- tools/rsdl/dotnet/rapid/ConsoleColorSelector.cs
- tools/rsdl/dotnet/rapid/CsdlFormat.cs
- tools/rsdl/dotnet/rapid/Program.cs
- tools/rsdl/dotnet/rapid/sample.rsdl
- tools/rsdl/dotnet/rsdl.models.transformation/ModelBuilder.cs
- tools/rsdl/dotnet/rsdl.models.transformation/ModelTransformer.cs
- tools/rsdl/dotnet/rsdl.models.transformation/TransformationException.cs
- tools/rsdl/dotnet/rsdl.models/rsdl/parser/AbstractSyntaxTree.cs
- tools/rsdl/dotnet/rsdl.parser/RdmParser.cs
- tools/rsdl/dotnet/rsdl.parser/RdmTokenizer.cs
Fixes oasis-open/odata-rapid#99
> add optional parameters to parser and transformation

- tools/rsdl/dotnet/rapid/sample.rsdl
- tools/rsdl/dotnet/rsdl.models.transformation/ModelBuilder.cs
> add date primitive type

- docs/rsdl/rapid-pro-rsdl-intro.md
- docs/spec/rapid-pro-resource_description.md
Updates RSDL introduction to align with Jetsons example.
Walks through building the schema incrementally.
Adds examples for complex types, enums, actions, functions, etc.
Makes GET methods live links to sample service
> Update RSDL Introduction

- docs/rsdl/rapid-pro-rsdl-abnf.md
> Include statement

- docs/rsdl/rapid-pro-rsdl-abnf.md
Keywords are case-sensitive and all-lower-case
Built-in types start with a Capital letter
> Case-sensitive strings

- docs/rsdl/rapid-pro-rsdl-intro.md
- docs/rsdl/rapid-pro-rsdl-semantics.md
Updates to rsdl-semantics based on agreed upon casing rules and default namespace/model naming.
> Casing model and schema naming

- tools/rsdl/dotnet/rapid.rdm.transformation.tests/TransformationTests.cs
- tools/rsdl/dotnet/rapid.rdm.transformation/ModelBuilder.cs
- tools/rsdl/dotnet/rapid.rdm.transformation/TypeMapping.cs
> generate keyless structural types as entity if used in singleton

- discussion/features.md
Discussion on feature scope for https://github.com/oasis-open/odata-rapid/issues/142
Feel free to comment, propose changes, or just change it.
> Feature Discussion

- tools/rsdl/rapid-cli/Microsoft.OData.Edm.Equivalency/SchemaDeltaBuilder.cs
- tools/rsdl/rapid-cli/rapid.rdm.transformation.tests/data/inheritance/sample.csdl.xml
- tools/rsdl/rapid-cli/rapid.rdm.transformation.tests/data/inheritance/sample.rsdl
- tools/rsdl/rapid-cli/rapid.rdm.transformation.tests/rapid.rdm.transformation.tests.csproj
- tools/rsdl/rapid-cli/rapid.rdm.transformation/ModelBuilder.cs
- tools/rsdl/rapid-cli/rapid.rdm.transformation/TopologicalOrder.cs
- tools/rsdl/rapid-cli/rapid.rdm/models/RdmStructuredType.cs
- tools/rsdl/rapid-cli/rapid.rsdl.tests/ModelEqualityTests.cs
- tools/rsdl/rapid-cli/rapid.rsdl.tests/ParserTests.cs
- tools/rsdl/rapid-cli/rapid.rsdl/Parsers.cs
- tools/rsdl/syntax-highlighting/syntaxes/rsdl.tmLanguage.json
> allow for inheritance of structured types

- tools/rsdl/rapid-cli/rapid/CsdlFormat.cs
- tools/rsdl/rapid-cli/rapid/Options.cs
- tools/rsdl/rapid-cli/rapid/OutputFormat.cs
- tools/rsdl/rapid-cli/rapid/RsdlConverter.cs
- tools/rsdl/rapid-cli/rapid/rapid.csproj
> Add support for OpenAPI Generation to Rapid-CLI.

- docs/rsdl/rapid-pro-rsdl-abnf.md
- tools/rsdl/rapid-cli/rapid.rdm.transformation.tests/data/parameter-annotations/model.csdl.xml
- tools/rsdl/rapid-cli/rapid.rdm.transformation.tests/data/parameter-annotations/model.rsdl
>  parameter annotations

- docs/rsdl/rapid-pro-rsdl-abnf.md
- docs/rsdl/rapid-pro-rsdl-intro.md
- docs/rsdl/rapid-pro-rsdl-semantics.mdx
- tools/rsdl/rapid-cli/rapid.rdm.transformation.tests/TransformationTests.cs
- tools/rsdl/rapid-cli/rapid.rdm.transformation/TypeEnvironment.cs
> add primitive types and test.

- docs/rsdl/rapid-pro-rsdl-abnf.md
Fixes https://github.com/oasis-open/odata-rapid/issues/207
> RSDL: optional service identifier

- website/docusaurus.config.js
- website/package.json
- website/src/css/custom.css
- website/src/pages/index.js
- website/static/img/logo.svg
- website/static/img/rabbit.svg
- docusaurus version updated to "2.0.0-alpha.75",
- logo is added as svg
open issues. 
- problem with changing small icon in top left (just replacing logo.svg with rabbit.svg is not working.
- placement of large logo in center needs more css finesse
> add logo, update version

- docs/rapid-pro.md
- docs/rsdl/rapid-pro-rsdl-semantics.mdx
- website/docusaurus.config.js
- website/package.json
Fixes #162
- Examples for String with and without MaxLength, and Decimal with and without Precision and Scale
Housekeeping
- Updated docusaurus to 2.0.0-beta.0
- Fixed warning for obsolete docusaurus construct
> Documentation of type facets

- docs/rsdl/rapid-pro-rsdl-abnf.md
> RSDL ABNF: typedef

- docs/rsdl/rapid-pro-rsdl-abnf.md
Define "precision", "scale", and "maxLength" as integers to convey semantics when defining facets.
> Define precision, scale, maxLength

- discussion/annotation-applicability.md
- docs/rsdl/rapid-pro-rsdl-abnf.md
- tools/rsdl/abnf/config.yaml
- tools/rsdl/abnf/lib/grammar.js
- tools/rsdl/abnf/rsdl-testcases.yaml
- tools/rsdl/abnf/rsdl.abnf
> RSDL ABNF: Annotations

- docs/rsdl/rapid-pro-rsdl-abnf.md
- tools/rsdl/abnf/lib/grammar.js
- tools/rsdl/abnf/lib/parse.js
- tools/rsdl/abnf/rsdl-testcases.yaml
- tools/rsdl/abnf/rsdl.abnf
and without redundant leading zeroes
Part of #228
> ABNF: Numbers with optional exponent and w/o redundant leading zeroes

- .github/workflows/node.js.yml
- .github/workflows/rapid-cli-ci.yml
- .github/workflows/website.yml
- CONTRIBUTING.md
- README.md
- tools/rsdl/README.md
- tools/rsdl/syntax-highlighting/package.json
- website/docusaurus.config.js
> renaming primary branch name

- docs/rsdl/rapid-pro-rsdl-abnf.md
- docs/rsdl/rapid-pro-rsdl-semantics.mdx
- tools/rsdl/abnf/lib/grammar.js
- tools/rsdl/abnf/lib/parse.js
- tools/rsdl/abnf/rsdl-testcases.yaml
- tools/rsdl/abnf/rsdl.abnf
> RSDL ABNF+Documentation: doc comments

- website/.prettierrc
- website/src/pages/index.js
... and prettier website/src/pages/index.js
> Center the rabbit

- docs/related/rapid-pro-graphql.md
- docs/samples/jetsons-sample-service.md
- docs/tutorial/graphqlclient.md
- samples/GraphQL_Client/.meshrc.yaml
- samples/GraphQL_Client/package.json
- website/README.md
- website/docusaurus.config.js
- website/sidebars.js
Fixes #288.
Fixes #287. 
Fixes #236.
> Add GraphQL Client Tutorial.

- tools/api-designer/package.json
- tools/odata-explorer/package.json
- tools/rsdlEditor/package.json
- tools/urlEditor/package.json
- tools/visualModelEditor/package.json
> Synced dependencies, fixed main

- website/package.json
- website/yarn.lock
> Upgrade docusaurus

- tools/odataUri/src/autocomplete-manager.ts
- tools/odataUri/test/autocomplete-manager.test.ts
> odataUri: completion at path segment end

- .vscode/settings.json
- .vscode/tasks.json
- package-lock.json
- package.json
- tools/rsdl/abnf/.prettierrc
- tools/rsdl/abnf/lib/check-abnf.ps1
- tools/rsdl/abnf/lib/extract.js
- tools/rsdl/abnf/package.json
- tools/rsdl/rsdl-js/.prettierrc
This PR contains parts of #441
> Add package tools/rsdl/abnf to monorepo

- package-lock.json
- tools/api-explorer/package.json
- tools/api-explorer/src/html/index.html
- tools/api-explorer/src/js/index.ts
Add support for CSDL-XML in API Explorer
Fix serialization in API Explorer
Misc other fixes
> API Explorer improvements
